### ISSUE TITLE
消息时间的显示问题

### ISSUE THREAD

**Issue by LAOMENGA** [netease-im/NIM_PC_Demo#11]
如果不下线的话，到第二天的时候前一天的消息时间显示还是今天几点几点，除非重新登录，切换会话也不会刷新。

**Comment by cqu227hk** [comment]
UI展示的时间是根据当时加载这条消息记录时生成的，不会随着时间而改变，是否可以通过其它交互来解决，比如说当时间跨过了一天后重新加载一次消息，切换会话并不能对消息重新加载

**Comment by LAOMENGA** [comment]
重新加载消息这一块，我试了下，我在当前代码没法实现啊
