### ISSUE TITLE
VS2013编译出错

### ISSUE THREAD

**Issue by Roat** [netease-im/NIM_PC_Demo#12]
1.错误	3	error C2065: “nick_full_name_”: 未声明的标识符	c:\users\cmic\downloads\nim_pc_demo-master\tool_kits\ui_component\ui_kit\gui\session\atlist\at_list_item.cpp

2.错误	7	error LNK1104: 无法打开文件“C:\Users\CMIC\Downloads\NIM_PC_Demo-master\libs\nim_ui_kit_d.lib”	C:\Users\CMIC\Downloads\NIM_PC_Demo-master\nim_win_demo\LINK	nim_demo

**Comment by cqu227hk** [comment]
单独编译一下“at_list_item.cpp”这个文件会报错吗？

**Comment by Roat** [comment]
> 单独编译一下“at_list_item.cpp”这个文件会报错吗？

单独编译也是这个错误， “nick_full_name_”这个变量在at_list_item.h定义了，而且已经包含进去了

**Comment by hurryerman** [comment]
这个错误是因为vs2013时  at_list_item.h文件保存的格式是 unicode(无签名utf8)  在文件--》高级保存--》保存为unicode(带签名utf8) 就可以了

**Comment by cqu227hk** [comment]
我们推荐的版本是vs2013 update5及以上。
