### ISSUE TITLE
vs2015 update3 编译不过

### ISSUE THREAD

**Issue by hurryerman** [netease-im/NIM_PC_Demo#13]
我看代码更新日志说更新了vs2015无法编译通过的问题 我所有工程全部改为v140了， 但是我的还是无法编译通过 第三方库 我编译了一部分 nim_demo一堆错误哦

而且官网提供的
https://dev.yunxin.163.com/docs/product/%E9%80%9A%E7%94%A8/%E6%96%B0%E6%89%8B%E6%8E%A5%E5%85%A5/%E5%8D%B3%E6%97%B6%E9%80%9A%E8%AE%AF/WindowsGettingStarted?#下载Demo源码

快速集成 vs2015也是通不过哦  第三方库的下载还不全-_-!!!

8>cef_module_d.lib(Window.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>cef_module_d.lib(Placeholder.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>cef_module_d.lib(WinImplBase.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>cef_module_d.lib(GlobalManager.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>cef_module_d.lib(Control.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>cef_module_d.lib(RichEdit.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>cef_module_d.lib(Box.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>cef_module_d.lib(Image.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>cef_module_d.lib(List.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>cef_module_d.lib(AnimationPlayer.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>cef_module_d.lib(VBox.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>cef_module_d.lib(ScrollBar.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>cef_module_d.lib(DpiManager.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>cef_module_d.lib(StringUtil.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>cef_module_d.lib(AnimationManager.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>cef_module_d.lib(Progress.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>cef_module_d.lib(TabBox.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>cef_module_d.lib(Combo.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>cef_module_d.lib(StdAfx.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>cef_module_d.lib(ApiWrapper.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>cef_module_d.lib(TimerManager.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>cef_module_d.lib(Shadow.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>cef_module_d.lib(IRender.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>cef_module_d.lib(Markup.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>cef_module_d.lib(WindowBuilder.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>cef_module_d.lib(Render.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>cef_module_d.lib(Define.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>cef_module_d.lib(HBox.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>cef_module_d.lib(TileBox.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>cef_module_d.lib(ChildBox.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>cef_module_d.lib(TreeView.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>cef_module_d.lib(Slider.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>cef_module_d.lib(VirtualListBox.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>cef_module_d.lib(Clip.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>cef_module_d.lib(Bitmap.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>nim_ui_kit_d.lib(capture_manager.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>nim_ui_kit_d.lib(capture_wnd.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>nim_ui_kit_d.lib(ui_color_palette.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>nim_ui_kit_d.lib(ui_capture_edit.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>nim_ui_kit_d.lib(capture_msg.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>nim_ui_kit_d.lib(draw_unit.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>nim_ui_kit_d.lib(ui_capture_text_edit.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>nim_ui_kit_d.lib(gauss_blur.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1800”不匹配值“1900”(nim_audio_cpp.obj 中)
8>libucrtd.lib(hypot.obj) : error LNK2005: _hypot 已经在 cef_module_d.lib(StdAfx.obj) 中定义
8>    正在创建库 F:\02CEF_NIM\NIM_PC_Demo-master_20190218\NIM_PC_Demo-master\nim_win_demo\..\bin\nim_demo_d.lib 和对象 F:\02CEF_NIM\NIM_PC_Demo-master_20190218\NIM_PC_Demo-master\nim_win_demo\..\bin\nim_demo_d.exp
8>LINK : warning LNK4199: 已忽略 /DELAYLOAD:libEGL.dll；未找到来自 libEGL.dll 的导入
8>LINK : warning LNK4199: 已忽略 /DELAYLOAD:libGLESv2.dll；未找到来自 libGLESv2.dll 的导入
8>nim_service_d.lib(local_helper.obj) : error LNK2001: 无法解析的外部符号 "protected: virtual void __thiscall TiXmlDocument::StreamIn(class std::basic_istream<char,struct std::char_traits<char> > *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?StreamIn@TiXmlDocument@@MAEXPAV?$basic_istream@DU?$char_traits@D@std@@@std@@PAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@@Z)
8>nim_ui_kit_d.lib(emoji_info.obj) : error LNK2001: 无法解析的外部符号 "protected: virtual void __thiscall TiXmlDocument::StreamIn(class std::basic_istream<char,struct std::char_traits<char> > *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?StreamIn@TiXmlDocument@@MAEXPAV?$basic_istream@DU?$char_traits@D@std@@@std@@PAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@@Z)
8>nim_ui_kit_d.lib(richedit_util.obj) : error LNK2001: 无法解析的外部符号 "protected: virtual void __thiscall TiXmlDocument::StreamIn(class std::basic_istream<char,struct std::char_traits<char> > *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?StreamIn@TiXmlDocument@@MAEXPAV?$basic_istream@DU?$char_traits@D@std@@@std@@PAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@@Z)
8>nim_ui_kit_d.lib(bubble_robot.obj) : error LNK2001: 无法解析的外部符号 "protected: virtual void __thiscall TiXmlDocument::StreamIn(class std::basic_istream<char,struct std::char_traits<char> > *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?StreamIn@TiXmlDocument@@MAEXPAV?$basic_istream@DU?$char_traits@D@std@@@std@@PAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@@Z)
8>chatroom_d.lib(chatroom_form_robot.obj) : error LNK2001: 无法解析的外部符号 "protected: virtual void __thiscall TiXmlDocument::StreamIn(class std::basic_istream<char,struct std::char_traits<char> > *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?StreamIn@TiXmlDocument@@MAEXPAV?$basic_istream@DU?$char_traits@D@std@@@std@@PAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@@Z)
8>addresbook_plugin_page.obj : error LNK2001: 无法解析的外部符号 "protected: virtual void __thiscall TiXmlDocument::StreamIn(class std::basic_istream<char,struct std::char_traits<char> > *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?StreamIn@TiXmlDocument@@MAEXPAV?$basic_istream@DU?$char_traits@D@std@@@std@@PAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@@Z)
8>main.obj : error LNK2001: 无法解析的外部符号 "protected: virtual void __thiscall TiXmlDocument::StreamIn(class std::basic_istream<char,struct std::char_traits<char> > *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?StreamIn@TiXmlDocument@@MAEXPAV?$basic_istream@DU?$char_traits@D@std@@@std@@PAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@@Z)
8>custom_app_sdk_d.lib(app_sdk_interface.obj) : error LNK2001: 无法解析的外部符号 "protected: virtual void __thiscall TiXmlDocument::StreamIn(class std::basic_istream<char,struct std::char_traits<char> > *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?StreamIn@TiXmlDocument@@MAEXPAV?$basic_istream@DU?$char_traits@D@std@@@std@@PAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@@Z)
8>nim_service_d.lib(login_manager.obj) : error LNK2001: 无法解析的外部符号 "protected: virtual void __thiscall TiXmlDocument::StreamIn(class std::basic_istream<char,struct std::char_traits<char> > *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?StreamIn@TiXmlDocument@@MAEXPAV?$basic_istream@DU?$char_traits@D@std@@@std@@PAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@@Z)
8>libeay32.lib(cryptlib.obj) : error LNK2019: 无法解析的外部符号 _vfprintf，该符号在函数 _OPENSSL_showfatal 中被引用
8>libeay32.lib(cryptlib.obj) : error LNK2019: 无法解析的外部符号 ___iob_func，该符号在函数 _OPENSSL_showfatal 中被引用
8>libeay32.lib(rsa_sign.obj) : error LNK2001: 无法解析的外部符号 ___iob_func
8>nim_ui_kit_d.lib(ui_color_palette.obj) : error LNK2001: 无法解析的外部符号 "class std::_Ph<1> std::placeholders::_1" (?_1@placeholders@std@@3V?$_Ph@$00@2@A)
8>cef_module_d.lib(Combo.obj) : error LNK2001: 无法解析的外部符号 "class std::_Ph<1> std::placeholders::_1" (?_1@placeholders@std@@3V?$_Ph@$00@2@A)
8>cef_module_d.lib(WindowBuilder.obj) : error LNK2001: 无法解析的外部符号 "class std::_Ph<1> std::placeholders::_1" (?_1@placeholders@std@@3V?$_Ph@$00@2@A)
8>cef_module_d.lib(TreeView.obj) : error LNK2001: 无法解析的外部符号 "class std::_Ph<1> std::placeholders::_1" (?_1@placeholders@std@@3V?$_Ph@$00@2@A)
8>nim_ui_kit_d.lib(capture_wnd.obj) : error LNK2001: 无法解析的外部符号 "class std::_Ph<1> std::placeholders::_1" (?_1@placeholders@std@@3V?$_Ph@$00@2@A)
8>cef_module_d.lib(Window.obj) : error LNK2001: 无法解析的外部符号 "class std::_Ph<1> std::placeholders::_1" (?_1@placeholders@std@@3V?$_Ph@$00@2@A)
8>cef_module_d.lib(WinImplBase.obj) : error LNK2001: 无法解析的外部符号 "class std::_Ph<1> std::placeholders::_1" (?_1@placeholders@std@@3V?$_Ph@$00@2@A)
8>cef_module_d.lib(Box.obj) : error LNK2001: 无法解析的外部符号 "class std::_Ph<1> std::placeholders::_1" (?_1@placeholders@std@@3V?$_Ph@$00@2@A)
8>cef_module_d.lib(AnimationManager.obj) : error LNK2001: 无法解析的外部符号 "class std::_Ph<1> std::placeholders::_1" (?_1@placeholders@std@@3V?$_Ph@$00@2@A)
8>nim_ui_kit_d.lib(gauss_blur.obj) : error LNK2001: 无法解析的外部符号 "char const * __cdecl std::_Winerror_map(int)" (?_Winerror_map@std@@YAPBDH@Z)
8>nim_ui_kit_d.lib(ui_capture_edit.obj) : error LNK2001: 无法解析的外部符号 "char const * __cdecl std::_Winerror_map(int)" (?_Winerror_map@std@@YAPBDH@Z)
8>nim_ui_kit_d.lib(capture_msg.obj) : error LNK2001: 无法解析的外部符号 "char const * __cdecl std::_Winerror_map(int)" (?_Winerror_map@std@@YAPBDH@Z)
8>nim_ui_kit_d.lib(draw_unit.obj) : error LNK2001: 无法解析的外部符号 "char const * __cdecl std::_Winerror_map(int)" (?_Winerror_map@std@@YAPBDH@Z)
8>nim_ui_kit_d.lib(ui_capture_text_edit.obj) : error LNK2001: 无法解析的外部符号 "char const * __cdecl std::_Winerror_map(int)" (?_Winerror_map@std@@YAPBDH@Z)
8>cef_module_d.lib(StdAfx.obj) : error LNK2001: 无法解析的外部符号 "char const * __cdecl std::_Winerror_map(int)" (?_Winerror_map@std@@YAPBDH@Z)
8>nim_ui_kit_d.lib(capture_manager.obj) : error LNK2001: 无法解析的外部符号 "char const * __cdecl std::_Winerror_map(int)" (?_Winerror_map@std@@YAPBDH@Z)
8>nim_ui_kit_d.lib(capture_wnd.obj) : error LNK2001: 无法解析的外部符号 "char const * __cdecl std::_Winerror_map(int)" (?_Winerror_map@std@@YAPBDH@Z)
8>nim_ui_kit_d.lib(ui_color_palette.obj) : error LNK2001: 无法解析的外部符号 "char const * __cdecl std::_Winerror_map(int)" (?_Winerror_map@std@@YAPBDH@Z)
8>nim_ui_kit_d.lib(richedit_util.obj) : error LNK2001: 无法解析的外部符号 "protected: virtual void __thiscall TiXmlText::StreamIn(class std::basic_istream<char,struct std::char_traits<char> > *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?StreamIn@TiXmlText@@MAEXPAV?$basic_istream@DU?$char_traits@D@std@@@std@@PAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@@Z)
8>nim_ui_kit_d.lib(capture_wnd.obj) : error LNK2001: 无法解析的外部符号 "class std::_Ph<2> std::placeholders::_2" (?_2@placeholders@std@@3V?$_Ph@$01@2@A)
8>nim_ui_kit_d.lib(gauss_blur.obj) : error LNK2019: 无法解析的外部符号 _printf_s，该符号在函数 "bool __cdecl ImageEffects::GaussianBlur(int,bool,bool,int,int,int,int,int,float,unsigned int *,unsigned int *)" (?GaussianBlur@ImageEffects@@YA_NH_N0HHHHHMPAI1@Z) 中被引用
8>cef_sandbox_d.lib(wmi.obj) : error LNK2019: 无法解析的外部符号 _CLSID_WbemLocator，该符号在函数 "bool __cdecl base::win::CreateLocalWmiConnection(bool,class Microsoft::WRL::ComPtr<struct IWbemServices> *)" (?CreateLocalWmiConnection@win@base@@YA_N_NPAV?$ComPtr@UIWbemServices@@@WRL@Microsoft@@@Z) 中被引用
8>F:\02CEF_NIM\NIM_PC_Demo-master_20190218\NIM_PC_Demo-master\nim_win_demo\..\bin\nim_demo_d.exe : fatal error LNK1120: 9 个无法解析的外部命令

**Comment by hurryerman** [comment]
希望能提供一个的可以编译通过的vs2015 update3的版本

**Comment by cqu227hk** [comment]
[6.0.0] - 2019-01-14
优化
调整C++封装层对VS2015及其以上版本的支持

为了方便开发者使用vs2015以及以上版本进行开发，对SDK/C++封装层进行了VS2015的支持改造。
对于demo及demo中使用的三方库以及cef模块未提供VS2015及以上版本的支持。
如果不使用CEF功能，可以考虑移除cef模块
