### ISSUE TITLE
点击nim_demo.exe，登录有没反应

### ISSUE THREAD

**Issue by sduqlsc** [netease-im/NIM_PC_Demo#16]
## 问题现象
git下载，解压lib包，VS选择nim_demo作为启动工程，属性选择Release，配置也选择Release，生成后，点击nim_demo.exe，登录有没反应。

debug下，nim_d.exe出现

 `Cannot use V8 Proxy resolver in single process mode.
[0830/092929:FATAL:nim_app.cpp(190)] Assert failed: ret. `

环境：VS2013 Update 5、windows 10

**Comment by nmgwddj** [comment]
请将 nim_demo 项目设置为启动项目。

**Comment by sduqlsc** [comment]
@nmgwddj 修改描述了，点击登录始终显示登录中……

**Comment by nmgwddj** [comment]
这个的确可能出现，因为 nim.dll、nim_chatroom.dll 等 SDK 文件均使用 VS2017 开发，而你本地只有 VS2013 的运行时环境，所以可能是缺少 VC++ 2017 运行时库导致的，可以单独安装微软 VC++ 2017 可在发行组件包来解决这个问题：https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by sduqlsc** [comment]
@nmgwddj 感谢回复，把所有的C++运行库都装上了，可以运行了
