### ISSUE TITLE
在Visual Studio 2013 Update 5 版本中运行错误

### ISSUE THREAD

**Issue by bxl0608** [netease-im/NIM_PC_Demo#17]
按照Readme的步骤无法正常运行项目，提示错误，fatal error LNK1104: 无法打开文件“D:\NIM_PC_Demo\libs\libcef_dll_wrapper_d.lib

**Comment by nmgwddj** [comment]
请提交具体错误内容，有助于我们帮助你分析问题。

**Comment by nmgwddj** [comment]
nim_demo 工程依赖 libcef_dll_wrapper 工程，这个可能是我们在整理项目的时候没有把该工程设置为依赖或者引用导致没有自动编译这个项目。

您可以手动将 libcef_dll_wrapper 工程设置为 nim_demo 的依赖或者引用，保证在 nim_demo 编译之前编译出来就可以了。

**Comment by bxl0608** [comment]
好的，我试一下

**Comment by bxl0608** [comment]
可以编译了，谢谢，但是另外的问题出现了。
我编译完成运行后，登陆账号，无法获取到最近消息和群列表。
如果我在手机云信登陆跟电脑版相同的账号，在手机上随便一个高级群发送一个消息之后，电脑版云信会崩溃

**Comment by bxl0608** [comment]
而且我下载最新版的代码之后，编译运行的结果是云信6.7.0.1547版本
![image](https://user-images.githubusercontent.com/25519786/64362970-17f71b00-d042-11e9-9499-39db9b31999d.png)

**Comment by nmgwddj** [comment]
@bxl0608 崩溃的原因是什么？如果是本地编译的，调试模式下崩溃很容易可以看到崩溃时的栈信息，是在上层 Demo 代码的崩溃还是 SDK 端的崩溃呢？

**Comment by bxl0608** [comment]
我设置release编译就不崩溃了，谢谢你

**Comment by nmgwddj** [comment]
Release 下可能只是避免了这个问题，建议您还是 Debug 模式下调试一下看看具体错误产生在哪里。

**Comment by bxl0608** [comment]
@

**Comment by bxl0608** [comment]
@nmgwddj

**Comment by nmgwddj** [comment]
@bxl0608 请参考 NIM DuiLib - EndDown 接口：https://github.com/netease-im/NIM_Duilib_Framework/blob/master/docs/Containers/ScrollableBox.md#EndDown

您反馈的问题可以当做 Bug 单独提交一个 Issue，每个 Issue 单独针对一个问题讨论。这样有助于其他人遇到相同问题时，可以通过 Issue 搜索的方式更快的获取到答案，避免重复提问。
