### ISSUE TITLE
群最新消息收到后无法在listbox底部展示

### ISSUE THREAD

**Issue by bxl0608** [netease-im/NIM_PC_Demo#18]
## 问题现象
当新的群消息到来后，打开群消息对话box，listbox在顶部问题
## 重现步骤

1.登录云信，随便打开一个群，此时消息是在最底部，当去到了别的对话框，然后这时群消息来了一条消息。
2.打开这个消息之后，显示的不是最新的消息。
3.EndDown接口我读到了，但是session_box代码读的时候，在打开消息对话框之后，有一个查询历史消息的回调,调用showMsgs方法，for循环调用showMsg方法，我在for循环之后加入list_box_->EndDown(true,false):方法无效。

**Comment by bxl0608** [comment]
有没有啥进展情况呀

**Comment by nmgwddj** [comment]
@bxl0608 https://github.com/netease-im/NIM_PC_Demo/commit/5b4c0851e8f84a267f85603d4de45c7b173aeb98 尝试修复了这个问题，您可以参考 development 分支的这次提交。

NIM Demo 是基于 NIM SDK 开发的示例应用，代码完全开放（包含 UI 框架 NIM Duilib），您在遇到问题时可以尽量尝试通过源代码调试排查问题，一些修复我们可能会随版本发布，并不一定是即时的。
