### ISSUE TITLE
你好，为什么注册后，无法登陆，返回错误码是302

### ISSUE THREAD

**Issue by stone-jin** [netease-im/NIM_PC_Demo#2]
1.不修改任何代码，然后注册账号，然后登陆，返回错误码是302
2.然后修改其中的appkey，使用自己在网易云信上面注册的账号，用appkey，也是返回错误码302，提示用户名密码错误。

**Comment by redrains** [comment]
你好，你的问题可以查看云信文档：http://dev.netease.im/docs?doc=faq&#PC版SDK

**Comment by stone-jin** [comment]
成功登陆了，代码中默认是md5加密的，线上服务器是不加密的，FAQ上面有....
