### ISSUE TITLE
能不能把编译好的也放上来

### ISSUE THREAD

**Issue by tornodo** [netease-im/NIM_PC_Demo#23]
目前就一个NIM_Education_PC_Demo能编译 通过，想看看界面效果，但是怎么也无法编译过去，官方能不能把编译好的二进制放出来呢？

**Comment by nmgwddj** [comment]
请参考云信官网：https://yunxin.163.com/im-demo

https://yx-web-nosdn.netease.im/package/1568898298/NIM_PC_Demo_Setup_v6.9.0.exe?download=NIM_PC_Demo_Setup_v6.9.0.exe

**Comment by nmgwddj** [comment]
另外你描述的无法编译过去具体编译的错误是什么，能否提供详细的错误信息有助于我们解决这些问题。
