### ISSUE TITLE
云信消息提醒

### ISSUE THREAD

**Issue by bxl0608** [netease-im/NIM_PC_Demo#24]
## 问题现象
目前云信没有消息提醒，来消息没有消息提示。看资源文件中有消息提示声音文件，但是无效果。bug
## 重现步骤

1.接收消息
2.无任何消息提醒。

**Comment by nmgwddj** [comment]
NewUI（聚合模式）下禁用了这个消息提醒，`ring_.Play(RING_NEW_MESSAGE);` 跟踪源代码可以找到播放音频文件的逻辑，可以根据自己情况进行修改。
https://github.com/netease-im/NIM_PC_Demo/blob/290739beb217de399948dd7d046c133221aa1c21/tool_kits/ui_component/ui_kit/module/session/session_manager.cpp#L79
