### ISSUE TITLE
最新版7.1.0.408.0版本源码编译运行异常

### ISSUE THREAD

**Issue by bxl0608** [netease-im/NIM_PC_Demo#26]
## 问题现象
1.直接编译出来的源码，不做任何改动，会话界面无法显示最近会话内容。
2.高级群也无法创建，创建完毕就会显示您已退出该群！
![image](https://user-images.githubusercontent.com/25519786/71496377-fdb1a900-288d-11ea-8b96-6b0b921fea35.png)

## 重现步骤

1.
2.

**Comment by bxl0608** [comment]
![image](https://user-images.githubusercontent.com/25519786/71496439-42d5db00-288e-11ea-975a-a74465decb75.png)

**Comment by cqu227hk** [comment]
试着清除一下缓存再运行一下看看

**Comment by bxl0608** [comment]
您指的是哪个缓存呢？
