### ISSUE TITLE
VS2015及以上版本无法编译

### ISSUE THREAD

**Issue by BeNhNp** [netease-im/NIM_PC_Demo#29]
#13 提过类似的问题，但是我发现几位contributor完全不当回事，项目维护人员搞不清楚别人报错是什么原因，以为早就解决了。
目前该项目并不完整，就我编译的结果来看，libeay32、libcrypto、nls_play等无法通过编译生成lib，版本不匹配导致生成exe失败。
根据我的理解，主要原因是因为不想开源目前最有价值的部分代码，不过即使这样，提供编译好的dll调用接口也能接受，只发布个特定版本的lib库，导致高版本无法使用，是否有欠考虑？
建议开发人员自行下载项目，编译体验，感受一下。
另外，项目更新了，但是说明文档并未及时更新。

**Comment by nmgwddj** [comment]
Demo 上链接三方库使用编译好的 Libraries 主要考虑是使用者在编译时不需要再手动编译三方库从而增加开发门槛。我们也在想办法通过脚本来管理三方库，使编译流程可以适配不同的平台工具集版本。这个工作需要您给一些时间。
从目前您的情况来看，更建议您使用 Demo 匹配版本的工具链（v141），除播放器SDK、IMSDK外（动态形式链接），Demo 上展示功能均已经全部开源，包括 UI 框架的全部代码。
如果您的确无法使用 v141 的平台工具链，需要自己编译一些依赖的三方库为指定版本，并将项目所有平台工具集修改为你需要的版本，包括但不仅限于 libyuv、libyv、libcurl、jsoncpp、libcrypto 等，这些三方库均可以通过开源社区获取。

**Comment by BeNhNp** [comment]
已确认，最新版本 7.4 经过简单修改（注掉tool_kits\shared\modal_wnd\async_modal_runner.h中的_NODISCARD；修改nim_win_demo\module\msglog_manager\msglog_callback.cpp 中的两个C++17风格的 shared_ptr为std::shared_ptr<char>，修改警告）可以在vs2015上编译通过。
