### ISSUE TITLE
你好，将appkey替换成自己的appkey后，点击注册后提示appkey不是demo中指定的key

### ISSUE THREAD

**Issue by stone-jin** [netease-im/NIM_PC_Demo#3]
我在代码中搜索了这个错误信息，没有搜索到，请问是什么原因

**Comment by redrains** [comment]
你好，你的问题可以查看云信文档：http://dev.netease.im/docs?doc=faq&#PC版SDK

**Comment by redrains** [comment]
在bin目录的server_conf.txt文件中可以配置自己的appkey

**Comment by stone-jin** [comment]
没有看到这个server_conf.txt文件是否没合到线上来

**Comment by cqu227hk** [comment]
云信 im demo提供的注册功能只是针对dmeo的key的，如果要注册其它appkey的账号可以参考https://dev.yunxin.163.com/docs/product/IM%E5%8D%B3%E6%97%B6%E9%80%9A%E8%AE%AF/%E6%9C%8D%E5%8A%A1%E7%AB%AFAPI%E6%96%87%E6%A1%A3/%E7%BD%91%E6%98%93%E4%BA%91%E9%80%9A%E4%BF%A1ID
