### ISSUE TITLE
其他模块都编译过了 最后这个nim_demo编译报错

### ISSUE THREAD

**Issue by sanheiZY** [netease-im/NIM_PC_Demo#31]
## 重现步骤
![图片](https://user-images.githubusercontent.com/40047593/76592834-848e2d80-652f-11ea-9a7d-10fc0bdf5cef.png)
这个duilib.vcxproj是不是必须有的呀

**Comment by nmgwddj** [comment]
duilib 是必须要有的，这是展示 UI 的基础模块，请根据错误提示修改警告等级和禁止将错误视为警告标识。https://docs.microsoft.com/zh-cn/cpp/build/reference/wx-treat-linker-warnings-as-errors?view=vs-2019
