### ISSUE TITLE
VS2013 编译失败

### ISSUE THREAD

**Issue by shuilan0066** [netease-im/NIM_PC_Demo#32]
tool_kits\shared\modal_wnd\async_modal_runner.h(52): error C2144: syntax error : 'int' should be preceded by ';'
error C2433: '_NODISCARD' : 'friend' not permitted on data declarations

error C2238: unexpected token(s) preceding ';'

**Comment by hezikuangxiang** [comment]
遇到了同样问题，也是VS2013，求问这个问题解决掉了么？

**Comment by cqu227hk** [comment]
目前im demo的开发环境已经升级到vs2017了，建议使用vs2017进行编译，包括我们提供的lib库只提供了vs2017版本。

**Comment by xiaoyu21git** [comment]
不能用2013编译吗？

**Comment by nmgwddj** [comment]
> 不能用2013编译吗？
已经不在提供 VS2013 的编译支持。
