### ISSUE TITLE
VS2017编译不了 出现很多错误

### ISSUE THREAD

**Issue by shuilan0066** [netease-im/NIM_PC_Demo#38]
出现 
fatal error C1083: 无法打开包括文件: “corecrt.h”
fatal error C1083: 无法打开包括文件: “string.h”

fatal error C1083: 无法打开包括文件: “stddef.h”

等。。。。一系列错误

**Comment by cqu227hk** [comment]
在安装VS2017时有安装windows sdk吗？

**Comment by binson1015** [comment]
windows sdk 要安装那个版本？

**Comment by cqu227hk** [comment]
https://blog.csdn.net/weixin_43081805/article/details/100126713
https://blog.csdn.net/weixin_38383877/article/details/88410707
您看一下可不可以解决您的问题

**Comment by binson1015** [comment]
![image](https://user-images.githubusercontent.com/50687028/84728054-9bbf3a00-afba-11ea-842d-9696fbb6a0fd.png)
请问，shared 库 编译失败，这个是一样的原因么

**Comment by nmgwddj** [comment]
工程已经升级到 CMake 管理，可以根据自己需求生成 VS2017 工程。
