### ISSUE TITLE
nbase::UTF16ToUTF8 中文转换乱码

### ISSUE THREAD

**Issue by binson1015** [netease-im/NIM_PC_Demo#41]
中英文夹杂的字符串（如，文件中文路径），使用nbase::UTF16ToUTF8转换之后，中文部分变成了乱码；反过来转也是一样的情况。

**Comment by nmgwddj** [comment]
请注意 VisualStudio 调试情况下并不会按 UTF8 格式解析字符串信息。在调试监视中，将变量后加 `,s8` 可显示 UTF8 格式字符串。
