### ISSUE TITLE
capture_image 这一块会开源么？

### ISSUE THREAD

**Issue by vanehu** [netease-im/NIM_PC_Demo#43]
发现capture_image 这个模块只是一个库 如果我想升级一下编译器的话 好像就不行了
如果想替换成开源的那个dui模块 其他的代码可以稍微修改一下，但是这个模块引用的不太对就有点麻烦了

**Comment by nmgwddj** [comment]
https://github.com/netease-im/NIM_PC_Demo/tree/master/tool_kits/ui_component/capture_image

**Comment by vanehu** [comment]
谢谢，同步以前的代码发现没有 我更新一下镜像
