### ISSUE TITLE
README文件的一个小错误

### ISSUE THREAD

**Issue by haifenghuang** [netease-im/NIM_PC_Demo#63]
在`README.md`文件的【使用音视频 2.0 版本】这一节，其中的一个命令是这样的：

```
 cmake . -B build -G"Visual Studio 2017" -T"v141_xp" -DBUILD_WITH_NERTC_G2=ON -DCMAKE_BUILD_TYPE=Debug
```

应该更改成如下：
```
 cmake . -B build -G"Visual Studio 15 2017" -T"v141_xp" -DBUILD_WITH_NERTC_G2=ON -DCMAKE_BUILD_TYPE=Debug
```

**Comment by nmgwddj** [comment]
> 在`README.md`文件的【使用音视频 2.0 版本】这一节，其中的一个命令是这样的：
> 
> ```
>  cmake . -B build -G"Visual Studio 2017" -T"v141_xp" -DBUILD_WITH_NERTC_G2=ON -DCMAKE_BUILD_TYPE=Debug
> ```
> 
> 应该更改成如下：
> 
> ```
>  cmake . -B build -G"Visual Studio 15 2017" -T"v141_xp" -DBUILD_WITH_NERTC_G2=ON -DCMAKE_BUILD_TYPE=Debug
> ```

感谢反馈，已经在 develop 分支修复：https://github.com/netease-im/NIM_PC_Demo/commit/dc2c074d65bbbfcb152042105b6c09d720965a5c
