### ISSUE TITLE
你好，软件启动问题

### ISSUE THREAD

**Issue by ilaoQ** [netease-im/NIM_PC_Demo#8]
提示Core\Image.cpp 有问题
expression   status==Gdiplus::Ok

我在项目中没找到Image.cpp的文件呢

**Comment by JoeDD** [comment]
如果忽视这个问题，可以正常登录注册，但是登录以后就卡死了

**Comment by redrains** [comment]
expression status==Gdiplus::Ok的意思是没有加载到指定的图片，估计你在xml中设置的图片路径不对。release模式会去掉这个检查

**Comment by JoeDD** [comment]
是的，确实图片加载有问题。谢了

对了，项目中是不是.lib文件不完整，我添加了几个才运行正常的
