### ISSUE TITLE
vs 2017编译出错

### ISSUE THREAD

**Issue by lgs1212** [netease-im/NIM_PC_Demo#9]
错误	C2664	“std::shared_ptr<AsyncModalRunner>::shared_ptr(std::shared_ptr<AsyncModalRunner> &&) noexcept”: 无法将参数 1 从“AsyncModalRunner *”转换为“std::nullptr_t”	shared	g:\new_code\nim_education_pc_demo_v2.1.0\tool_kits\shared\modal_wnd\async_modal_runner.cpp	70

**Comment by quanzhuo** [comment]
@lgs1212 请问你编译过了吗？
